services:
  frontend-dev-service:
    image: frontend-dev-image
    container_name: frontend-dev-container
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    volumes:
      - .:/app
    tty: true